[0m17:18:44.340876 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000296B2003650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000296B2E87920>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000296B0FB9340>]}


============================== 17:18:44.343885 | 6022c1cb-d3ac-4428-b3d3-5002e9275ac1 ==============================
[0m17:18:44.343885 [info ] [MainThread]: Running with dbt=1.9.0
[0m17:18:44.344875 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Haroon\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:19:05.261989 [debug] [MainThread]: Starter project path: C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\include\starter_project
[0m17:19:05.290793 [info ] [MainThread]: 
Your new dbt project "data_pipeline" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m17:19:05.291796 [info ] [MainThread]: Setting up your profile.
[0m17:19:34.513727 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m17:19:34.514727 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m17:19:34.514727 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m22:01:51.111714 [error] [MainThread]: Encountered an error:

[0m22:01:51.177992 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\requires.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\main.py", line 477, in init
    results = task.run()
              ^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 346, in run
    self.setup_profile(profile_name)
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 262, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 179, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 163, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 129, in generate_target_from_input
    target[key] = click.prompt(
                  ^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m22:01:51.191166 [debug] [MainThread]: Command `dbt init` failed at 22:01:51.187507 after 16986.96 seconds
[0m22:01:51.199686 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000296B2EC3680>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000296C5B6A930>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000296C5947CB0>]}
[0m22:01:51.203600 [debug] [MainThread]: Flushing usage events
[0m22:01:51.747612 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m09:08:48.152356 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014BB2D3CE90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014BB2D3C4D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014BB2D3F350>]}


============================== 09:08:48.157460 | ca5d043e-def9-4dc5-aac9-4404c04c0968 ==============================
[0m09:08:48.157460 [info ] [MainThread]: Running with dbt=1.9.0
[0m09:08:48.158461 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\Haroon\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}
[0m09:08:56.102471 [info ] [MainThread]: A project called data_pipeline already exists here.
[0m09:08:56.103482 [debug] [MainThread]: Command `dbt init` succeeded at 09:08:56.103482 after 8.07 seconds
[0m09:08:56.104486 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014BB2BCEF30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014BB1A2C9E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014BB1A2EBA0>]}
[0m09:08:56.104486 [debug] [MainThread]: Flushing usage events
[0m09:08:56.629163 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m09:14:16.001705 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000194AD2F07A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000194AFC1B5C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000194AFC1AC60>]}


============================== 09:14:16.004715 | ea946df9-b70f-4b0a-99f9-2ccce19106fd ==============================
[0m09:14:16.004715 [info ] [MainThread]: Running with dbt=1.9.0
[0m09:14:16.005705 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Haroon\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}
[0m09:14:21.449698 [debug] [MainThread]: Starter project path: C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\include\starter_project
[0m09:14:21.480129 [info ] [MainThread]: 
Your new dbt project "data_pipeline" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m09:14:21.481165 [info ] [MainThread]: Setting up your profile.
[0m09:14:27.454930 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m09:14:27.456007 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m09:14:27.457011 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m09:36:39.756415 [error] [MainThread]: Encountered an error:

[0m09:36:39.805954 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\requires.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\main.py", line 477, in init
    results = task.run()
              ^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 346, in run
    self.setup_profile(profile_name)
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 262, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 179, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 163, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 129, in generate_target_from_input
    target[key] = click.prompt(
                  ^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m09:36:39.807942 [debug] [MainThread]: Command `dbt init` failed at 09:36:39.807942 after 1343.92 seconds
[0m09:36:39.808951 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000194AD381B80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000194A9F9D340>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000194C0AA7F20>]}
[0m09:36:39.808951 [debug] [MainThread]: Flushing usage events
[0m09:36:40.237213 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m09:36:51.360229 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B7D92CB710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B7D92C9F70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B7D92C92B0>]}


============================== 09:36:51.363239 | a6c71515-f9b5-458a-97e3-521460ba78cb ==============================
[0m09:36:51.363239 [info ] [MainThread]: Running with dbt=1.9.0
[0m09:36:51.364238 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\Haroon\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m09:37:02.427699 [debug] [MainThread]: Starter project path: C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\include\starter_project
[0m09:37:02.445837 [info ] [MainThread]: 
Your new dbt project "data_pipeline" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m09:37:02.446868 [info ] [MainThread]: Setting up your profile.
[0m09:37:05.302080 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m09:37:05.303080 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m09:37:05.303080 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m10:15:54.607658 [error] [MainThread]: Encountered an error:

[0m10:15:54.613652 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\requires.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\main.py", line 477, in init
    results = task.run()
              ^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 346, in run
    self.setup_profile(profile_name)
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 262, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 179, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 163, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 129, in generate_target_from_input
    target[key] = click.prompt(
                  ^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m10:15:54.617651 [debug] [MainThread]: Command `dbt init` failed at 10:15:54.616651 after 2343.37 seconds
[0m10:15:54.617651 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B7D6F49220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B7D2FE59D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B7EA3925A0>]}
[0m10:15:54.618650 [debug] [MainThread]: Flushing usage events
[0m10:15:55.038681 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m10:16:49.688564 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000235FDE5B8C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000235FDE586E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000235FDE5A390>]}


============================== 10:16:49.692074 | ecfc2f21-bfab-45d8-bda3-361e616749af ==============================
[0m10:16:49.692074 [info ] [MainThread]: Running with dbt=1.9.0
[0m10:16:49.693065 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\Haroon\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m10:16:54.659357 [debug] [MainThread]: Starter project path: C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\include\starter_project
[0m10:16:54.674590 [info ] [MainThread]: 
Your new dbt project "data_pipeline" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m10:16:54.675592 [info ] [MainThread]: Setting up your profile.
[0m10:17:05.148241 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m10:17:05.148241 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m10:17:05.149241 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m10:17:39.754420 [error] [MainThread]: Encountered an error:

[0m10:17:39.760415 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\requires.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\main.py", line 477, in init
    results = task.run()
              ^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 346, in run
    self.setup_profile(profile_name)
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 262, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 179, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 163, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 129, in generate_target_from_input
    target[key] = click.prompt(
                  ^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m10:17:39.762617 [debug] [MainThread]: Command `dbt init` failed at 10:17:39.762617 after 50.19 seconds
[0m10:17:39.763617 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000235FD91FFB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002359067B1A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002359067BF50>]}
[0m10:17:39.763617 [debug] [MainThread]: Flushing usage events
[0m10:17:40.222232 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m10:17:55.094668 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E36131F1D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E36131CA40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E36131D850>]}


============================== 10:17:55.098205 | 7b01c292-e129-4fee-9009-7e0df354bdcf ==============================
[0m10:17:55.098205 [info ] [MainThread]: Running with dbt=1.9.0
[0m10:17:55.098205 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\Haroon\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m10:18:00.137284 [debug] [MainThread]: Starter project path: C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\include\starter_project
[0m10:18:00.157654 [info ] [MainThread]: 
Your new dbt project "data_pipeline" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m10:18:00.158664 [info ] [MainThread]: Setting up your profile.
[0m10:18:02.226687 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m10:18:02.227688 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m10:18:02.227688 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m14:07:14.400635 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C46CF7DFA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C46CB73740>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C46CEA87D0>]}


============================== 14:07:14.404912 | 66435723-4062-4e32-957e-de9b984874dc ==============================
[0m14:07:14.404912 [info ] [MainThread]: Running with dbt=1.9.0
[0m14:07:14.405515 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\Haroon\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt init', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:07:19.915524 [debug] [MainThread]: Starter project path: C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\include\starter_project
[0m14:07:19.942698 [info ] [MainThread]: 
Your new dbt project "data_pipeline" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:07:19.943698 [info ] [MainThread]: Setting up your profile.
[0m14:07:26.493153 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m14:07:26.494149 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m14:07:26.495146 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m14:17:47.758265 [info ] [MainThread]: Profile data_pipeline written to C:\Users\Haroon\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m14:17:47.760259 [debug] [MainThread]: Command `dbt init` succeeded at 14:17:47.760259 after 633.50 seconds
[0m14:17:47.761255 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C46D2D7740>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C46D32BEC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C47FD94650>]}
[0m14:17:47.761255 [debug] [MainThread]: Flushing usage events
[0m14:17:48.328289 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:17:58.427282 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022A7EFEE3C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022A7FB5E090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022A7FB5F110>]}


============================== 14:17:58.431275 | 28aa9ea7-b316-4e15-b274-ae868a11205c ==============================
[0m14:17:58.431275 [info ] [MainThread]: Running with dbt=1.9.0
[0m14:17:58.432270 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Haroon\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt debug', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:17:58.451620 [info ] [MainThread]: dbt version: 1.9.0
[0m14:17:58.452617 [info ] [MainThread]: python version: 3.12.7
[0m14:17:58.452617 [info ] [MainThread]: python path: C:\Users\Haroon\AppData\Local\Programs\Python\Python312\python.exe
[0m14:17:58.452617 [info ] [MainThread]: os info: Windows-10-10.0.19045-SP0
[0m14:17:58.997848 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m14:17:58.997848 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m14:17:58.998885 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m14:17:59.496325 [info ] [MainThread]: Using profiles dir at C:\Users\Haroon\.dbt
[0m14:17:59.497251 [info ] [MainThread]: Using profiles.yml file at C:\Users\Haroon\.dbt\profiles.yml
[0m14:17:59.497251 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\Haroon\Documents\GitHub\end_to_end_databricks_apache_airflow_dbt_project\dbt_project.yml
[0m14:17:59.498245 [info ] [MainThread]: adapter type: databricks
[0m14:17:59.499081 [info ] [MainThread]: adapter version: 1.9.0
[0m14:17:59.499551 [info ] [MainThread]: Configuration:
[0m14:17:59.500086 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m14:17:59.500086 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m14:17:59.501084 [info ] [MainThread]: Required dependencies:
[0m14:17:59.501084 [debug] [MainThread]: Executing "git --help"
[0m14:17:59.517985 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m14:17:59.517985 [debug] [MainThread]: STDERR: "b''"
[0m14:17:59.517985 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m14:17:59.519457 [info ] [MainThread]: Connection:
[0m14:17:59.519666 [info ] [MainThread]:   host: dbc-0a97f324-9d53.cloud.databricks.com
[0m14:17:59.519666 [info ] [MainThread]:   http_path: /sql/1.0/warehouses/1a2edc6dcad599b8
[0m14:17:59.520765 [info ] [MainThread]:   catalog: samples
[0m14:17:59.520765 [info ] [MainThread]:   schema: tpch
[0m14:17:59.521761 [info ] [MainThread]: Registered adapter: databricks=1.9.0
[0m14:17:59.899921 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2379718385280, session-id=None, name=debug, idle-time=0s, acquire-count=0, language=None, thread-identifier=(2892, 13636), compute-name=) - Creating connection
[0m14:17:59.899921 [debug] [MainThread]: Acquiring new databricks connection 'debug'
[0m14:17:59.900927 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2379718385280, session-id=None, name=debug, idle-time=0.0s, acquire-count=1, language=None, thread-identifier=(2892, 13636), compute-name=) - Acquired connection on thread (2892, 13636), using default compute resource
[0m14:17:59.900927 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2379718385280, session-id=None, name=debug, idle-time=0.0s, acquire-count=1, language=None, thread-identifier=(2892, 13636), compute-name=) - Checking idleness
[0m14:17:59.900927 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2379718385280, session-id=None, name=debug, idle-time=0.0s, acquire-count=1, language=None, thread-identifier=(2892, 13636), compute-name=) - Retrieving connection
[0m14:17:59.900927 [debug] [MainThread]: Using databricks connection "debug"
[0m14:17:59.901839 [debug] [MainThread]: On debug: select 1 as id
[0m14:17:59.901839 [debug] [MainThread]: Opening a new connection, currently in state init
[0m14:18:00.434584 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2379718385280, session-id=01efb7ca-ba58-1be7-bb20-fe3472ff67a1, name=debug, idle-time=0.0s, acquire-count=1, language=None, thread-identifier=(2892, 13636), compute-name=) - Connection created
[0m14:18:00.435505 [debug] [MainThread]: Databricks adapter: Cursor(session-id=01efb7ca-ba58-1be7-bb20-fe3472ff67a1, command-id=Unknown) - Created cursor
[0m14:18:01.065243 [debug] [MainThread]: SQL status: OK in 1.160 seconds
[0m14:18:01.067236 [debug] [MainThread]: Databricks adapter: Cursor(session-id=01efb7ca-ba58-1be7-bb20-fe3472ff67a1, command-id=01efb7ca-ba6d-1747-bf39-787dfdec71fa) - Closing cursor
[0m14:18:01.067236 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2379718385280, session-id=01efb7ca-ba58-1be7-bb20-fe3472ff67a1, name=debug, idle-time=0.0s, acquire-count=0, language=None, thread-identifier=(2892, 13636), compute-name=) - Released connection
[0m14:18:01.068232 [info ] [MainThread]:   Connection test: [[32mOK connection ok[0m]

[0m14:18:01.069289 [info ] [MainThread]: [31m1 check failed:[0m
[0m14:18:01.070378 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\Haroon\Documents\GitHub\end_to_end_databricks_apache_airflow_dbt_project\dbt_project.yml> not found

[0m14:18:01.072365 [debug] [MainThread]: Command `dbt debug` failed at 14:18:01.071393 after 2.79 seconds
[0m14:18:01.072365 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m14:18:01.072365 [debug] [MainThread]: On debug: Close
[0m14:18:01.073362 [debug] [MainThread]: Databricks adapter: Connection(session-id=01efb7ca-ba58-1be7-bb20-fe3472ff67a1) - Closing connection
[0m14:18:01.246749 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022A7F429640>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022A1239EDB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022A7F8667B0>]}
[0m14:18:01.248740 [debug] [MainThread]: Flushing usage events
[0m14:18:01.665700 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:41:29.702606 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000130389FCE00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000130389FE840>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000130389FFA40>]}


============================== 14:41:29.706605 | f9c1b36e-635f-4cfa-abaa-931ae72caf39 ==============================
[0m14:41:29.706605 [info ] [MainThread]: Running with dbt=1.9.0
[0m14:41:29.706605 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Haroon\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt deps', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:41:29.707601 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Haroon\Documents\GitHub\end_to_end_databricks_apache_airflow_dbt_project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:41:29.708597 [debug] [MainThread]: Command `dbt deps` failed at 14:41:29.708597 after 0.14 seconds
[0m14:41:29.708597 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013036675760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000130379EA030>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000130389FE8D0>]}
[0m14:41:29.708597 [debug] [MainThread]: Flushing usage events
[0m14:41:30.131976 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:42:42.097374 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000286BDED8B60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000286BD0AA180>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000286BDB5E180>]}


============================== 14:42:42.101374 | a7d2ccfc-3b92-4461-b824-2a2e3586998d ==============================
[0m14:42:42.101374 [info ] [MainThread]: Running with dbt=1.9.0
[0m14:42:42.101374 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\Haroon\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:42:42.116688 [info ] [MainThread]: dbt version: 1.9.0
[0m14:42:42.117694 [info ] [MainThread]: python version: 3.12.7
[0m14:42:42.117694 [info ] [MainThread]: python path: C:\Users\Haroon\AppData\Local\Programs\Python\Python312\python.exe
[0m14:42:42.118682 [info ] [MainThread]: os info: Windows-10-10.0.19045-SP0
[0m14:42:42.666718 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m14:42:42.667726 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m14:42:42.667726 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m14:42:43.193377 [info ] [MainThread]: Using profiles dir at C:\Users\Haroon\.dbt
[0m14:42:43.194451 [info ] [MainThread]: Using profiles.yml file at C:\Users\Haroon\.dbt\profiles.yml
[0m14:42:43.195258 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\Haroon\Documents\GitHub\end_to_end_databricks_apache_airflow_dbt_project\dbt_project.yml
[0m14:42:43.195800 [info ] [MainThread]: adapter type: databricks
[0m14:42:43.196345 [info ] [MainThread]: adapter version: 1.9.0
[0m14:42:43.196881 [info ] [MainThread]: Configuration:
[0m14:42:43.196881 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m14:42:43.197968 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m14:42:43.197968 [info ] [MainThread]: Required dependencies:
[0m14:42:43.198907 [debug] [MainThread]: Executing "git --help"
[0m14:42:43.215209 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m14:42:43.216287 [debug] [MainThread]: STDERR: "b''"
[0m14:42:43.216287 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m14:42:43.217008 [info ] [MainThread]: Connection:
[0m14:42:43.218015 [info ] [MainThread]:   host: dbc-0a97f324-9d53.cloud.databricks.com
[0m14:42:43.218015 [info ] [MainThread]:   http_path: /sql/1.0/warehouses/1a2edc6dcad599b8
[0m14:42:43.219013 [info ] [MainThread]:   catalog: samples
[0m14:42:43.219013 [info ] [MainThread]:   schema: tpch
[0m14:42:43.220010 [info ] [MainThread]: Registered adapter: databricks=1.9.0
[0m14:42:43.417129 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2778021310400, session-id=None, name=debug, idle-time=0s, acquire-count=0, language=None, thread-identifier=(5244, 2768), compute-name=) - Creating connection
[0m14:42:43.417129 [debug] [MainThread]: Acquiring new databricks connection 'debug'
[0m14:42:43.417129 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2778021310400, session-id=None, name=debug, idle-time=0.0s, acquire-count=1, language=None, thread-identifier=(5244, 2768), compute-name=) - Acquired connection on thread (5244, 2768), using default compute resource
[0m14:42:43.417129 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2778021310400, session-id=None, name=debug, idle-time=0.0s, acquire-count=1, language=None, thread-identifier=(5244, 2768), compute-name=) - Checking idleness
[0m14:42:43.418121 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2778021310400, session-id=None, name=debug, idle-time=0.0009915828704833984s, acquire-count=1, language=None, thread-identifier=(5244, 2768), compute-name=) - Retrieving connection
[0m14:42:43.418121 [debug] [MainThread]: Using databricks connection "debug"
[0m14:42:43.418121 [debug] [MainThread]: On debug: select 1 as id
[0m14:42:43.418121 [debug] [MainThread]: Opening a new connection, currently in state init
[0m14:42:44.116158 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2778021310400, session-id=01efb7ce-2ea3-1d96-a4df-20d60ade3c49, name=debug, idle-time=0.0s, acquire-count=1, language=None, thread-identifier=(5244, 2768), compute-name=) - Connection created
[0m14:42:44.117222 [debug] [MainThread]: Databricks adapter: Cursor(session-id=01efb7ce-2ea3-1d96-a4df-20d60ade3c49, command-id=Unknown) - Created cursor
[0m14:42:50.993319 [debug] [MainThread]: SQL status: OK in 7.570 seconds
[0m14:42:50.993319 [debug] [MainThread]: Databricks adapter: Cursor(session-id=01efb7ce-2ea3-1d96-a4df-20d60ade3c49, command-id=01efb7ce-2ecc-10c2-a36e-fc11722315bc) - Closing cursor
[0m14:42:51.285192 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2778021310400, session-id=01efb7ce-2ea3-1d96-a4df-20d60ade3c49, name=debug, idle-time=0.0s, acquire-count=0, language=None, thread-identifier=(5244, 2768), compute-name=) - Released connection
[0m14:42:51.286186 [info ] [MainThread]:   Connection test: [[32mOK connection ok[0m]

[0m14:42:51.287711 [info ] [MainThread]: [31m1 check failed:[0m
[0m14:42:51.288718 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\Haroon\Documents\GitHub\end_to_end_databricks_apache_airflow_dbt_project\dbt_project.yml> not found

[0m14:42:51.289714 [debug] [MainThread]: Command `dbt debug` failed at 14:42:51.289714 after 9.31 seconds
[0m14:42:51.290711 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m14:42:51.290711 [debug] [MainThread]: On debug: Close
[0m14:42:51.290711 [debug] [MainThread]: Databricks adapter: Connection(session-id=01efb7ce-2ea3-1d96-a4df-20d60ade3c49) - Closing connection
[0m14:42:51.459968 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000286BD68AB70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000286CEF92FC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000286CF490260>]}
[0m14:42:51.461042 [debug] [MainThread]: Flushing usage events
[0m14:42:51.906382 [debug] [MainThread]: An error was encountered while trying to flush usage events
